import { dagen, dannyg, andrew, courtney, artists_2, developers, nerds } from './assets/images';

export const data = [
	{ id: 'dagen', name: 'DAGEN', text: 'The Ruler of the Universe. Operations Management and Marketing wizard.', title: 'Founder', body: 'The Ruler of the Universe. Operations Management and Marketing wizard.', img: dagen },
	{ id: 'dannyg', name: 'DANNYG', text: '69x cooler than Dagen. Artist Management and Direction.', title: 'Co-founder', body: '69x cooler than Dagen. Artist Management and Direction.', img: dannyg },
	{ id: 'andrew', name: 'ANDREW', text: 'Handles the layout of the universe. Blame him if your planet is far away.', title: 'Degenerate', body: 'Degenerate shitcoiner. Handles the layout of the universe. Blame him if your planet is far away.', img: andrew },
	{ id: 'nerds', name: 'GAME DEVELOPERS', text: 'The brains behind the games. Established studio building the Borgverse.', title: 'The Brains', body: 'We have a constantly expanding game development team as we are continually searching for new talent. Currently our developer team consists of Martian Games as well as a few other developers that we have brought onto the team to help us progress at a faster pace. Martian Games has been creating indie games as well as working for large gaming studios for over 13 years now, with their indie games amassing millions of unique users. After consulting with several studios we went with the Martian team as they have tons of experience when it comes to multiplayer mechanics as well as sci-fi themed games which is a core feature that all planets in the Borgverse have. Over the last few months we have been actively searching and adding new developers to our team that specialize in different sectors of the gaming industry to allow us to create a truly unique gaming experience on every planet. If you are a game developer or highly experienced artist please reach out to us on twitter as we are always looking to add new talent to our expanding team!', img: nerds },
	{ id: 'courtney', name: 'COURTNEY', text: 'Eats sushi all day and focuses on finding new talent.', title: 'The Queen', body: 'Eats sushi all day and focuses on finding new talent.', img: courtney },
	{ id: 'artists', name: 'ARTISTS', text: '7 elite individuals working with us to create some cool ass shit. ', title: 'The GOATs', body: 'Our art team consists of 7 extremely talented artists that all specialize in different sectors of art for our project. From the bots, to the bunkers, to the planets, to the robotic arms, and much more. Our artists focus on perfection and delivering an amazing product to you all.', img: artists_2 },
	{ id: 'developers', name: 'DEVELOPERS', text: '3 backend developers, 12 brains, seriously these guys have giga brains.', title: 'Backend Developers', body: 'Our dev team currently consists of 3 developers with experience in both the eth and sol space. Our devs delegate their time to the integration of web 3 for the Borgverse. We are constantly looking to add more developers to our team and have been in talks with several reputable devs from the space. We understand that for a project like ours to thrive, there must be extremely capable developers and visionaries behind it.', img: developers },
];
